// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package stem

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "GoWeb/pages/layout"
import "GoWeb/pages"

func getPDFS() string {
	return "/wwwroot/pdfs/EngineeringDynamics7ed.pdf"
}

func StemPdfPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.PageTemplateHead("Stem PDF's").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = layout.Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = layout.PageTemplateBody(pages.Unsafe(
			`
    <h1>Stem PDF's</h1>
    <hr/>
    <h4>This is a page dedicated to all STEM PDF's that I've found and want others to use and Download.</h4>

    <!--Show Stem PDFS-->
    <hr/>
    <h2> Free Online STEM PDF's: </h2>
    <embed class="pdf" src="/wwwroot/pdfs/EngineeringDynamics7ed.pdf" width="800px" height="1000px"/>
    <embed class="pdf" src="/wwwroot/pdfs/LinearAlgebra.pdf" width="800px" height="1000px"/>
    <embed class="pdf" src="/wwwroot/pdfs/Thomas_Calculus.pdf" width="800px" height="1000px" />
    <embed class="pdf" src="/wwwroot/pdfs/learnOpengl.pdf" width="800px" height="1000px" />
    <embed class="pdf" src="/wwwroot/pdfs/GameEngineDesign.pdf" width="800px" height="1000px" />
  `)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = layout.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
